### ISSUE TITLE
Error outputs and handling for a test cases

### ISSUE THREAD

**Issue by WilstonOreo** [Rustfahrtagentur/microcad#16]
I want to test the error outputs for the parser specifically.
Let's say, we have an error in the module, I like to have the error output similar to the rust compiler:

```µcad
Error[E033]: No variable, module or function named "sphere"
   --> example.µcad:1:6
    | 
1   | geo3d::sphere(r = 24mm);
    |        ^^^^^^
    |        Help: There is a module `sphere` in `geo3d`.
    |        Perhaps you forgot to add a use statement `use geo3d::sphere;`?
```

We should have an id and one test case for each error.
If we write the test cases like this:

```µcad
geo3d::sphere(r = 24mm);
       ^^^^^^Error[E033]
```

`^^^^^^` denotes the span in which the error occured. Its position must also be verified in the test case.

**Comment by fightling** [comment]
this is solved.
