### ISSUE TITLE
Enforce statement order in libraries

### ISSUE THREAD

**Issue by WilstonOreo** [Rustfahrtagentur/microcad#46]
For cleaner library source code, it might make sense to enfore a certain order of statements. E.g., it might be good to declare all use statements on top of the file, global constants afterwards, and so on:

```
use std::*; // Use statement first
PI = 3.1514; // Some global constants
namespace {} // Namespaces
function a() {} // Functions
module b() {} // Modules
```

If this order is not kept, a warning should be displayed that this source file cannot be imported as a library.

**Comment by fightling** [comment]
I don't think so!

This is important in modules but in the outer, global code we just deal with the *user* who programs his idea, maybe without no further programming knowledge.

So leave the user alone!

I think instead we shall take more care about, to make modules the only objects that can be use from outside files and **no** functions and constants (only if they are packed in a module which can be addressed by `use`).
This would force a correct source code order in libraries but the user is more free in the use case code.

**Comment by WilstonOreo** [comment]
To be discussed later
