### ISSUE TITLE
split module `std` into `std` and `builtin`

### ISSUE THREAD

**Issue by fightling** [Rustfahrtagentur/microcad#60]
Because standard library might grow in future and separate into several files it should be in a separate directory.
Currently it is put beside the builtin modules within `std`.

**Comment by WilstonOreo** [comment]
I suggest we put the builtin stuff into a microcad-builtin crate and leave the std stuff in the microcad-std crate.

**Comment by fightling** [comment]
@WilstonOreo is this done?
